const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Sprite6: 0},
	{Sprite7: 0},
	{FundoDeTela: 0},
	{Fixar: 0},
	{animaçao: 0},
	{Sólido: 0},
	{plataforma: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{jogador: 0},
	{Teclado: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Senóide: 0},
	{moeda: 0},
	{Âncora: 0},
	{Pontos: 0},
	{Sprite: 0},
	{ação: 0},
	{ação2: 0},
	{zumbi: 0},
	{marcador: 0},
	{gameOver: 0},
	{Sprite2: 0},
	{Jogar: 0},
	{Texto: 0},
	{Sprite3: 0},
	{Texto2: 0},
	{Áudio: 0},
	{lava: 0},
	{FundoDeTela2: 0},
	{FundoDeTela3: 0},
	{FundoDeTela4: 0},
	{FundoDeTela5: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{FundoDeTela6: 0},
	{FundoDeTela7: 0}
];

self.InstanceType = {
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	FundoDeTela: class extends self.ISpriteInstance {},
	animaçao: class extends self.ISpriteInstance {},
	plataforma: class extends self.ITiledBackgroundInstance {},
	jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	moeda: class extends self.ISpriteInstance {},
	Pontos: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	zumbi: class extends self.ISpriteInstance {},
	marcador: class extends self.ISpriteInstance {},
	gameOver: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Jogar: class extends self.IButtonInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	lava: class extends self.ISpriteInstance {},
	FundoDeTela2: class extends self.ISpriteInstance {},
	FundoDeTela3: class extends self.ISpriteInstance {},
	FundoDeTela4: class extends self.ISpriteInstance {},
	FundoDeTela5: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	FundoDeTela6: class extends self.ISpriteInstance {},
	FundoDeTela7: class extends self.ISpriteInstance {}
}